# Generated by Django 5.1.3 on 2024-11-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='servicos_adicionais',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='protocole',
            new_name='protocolo',
        ),
        migrations.DeleteModel(
            name='ServicoAdicional',
        ),
    ]
